version: '3.8'

services:
  redis:
    image: redis:alpine
    container_name: redis
    networks:
      - redis_network
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: app
    networks:
      - redis_network
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379

networks:
  redis_network:
    external: true

volumes:
  redis-data:
