version: '3'
services:
  redis:
    image: "redis:alpine"
    container_name: redis
    ports:
      - "6379:6379"
  
  mqtt_broker:
    image: "eclipse-mosquitto"
    container_name: mqtt_broker
    ports:
      - "1883:1883"

  fornecedor:
    build: ./fornecedor
    depends_on:
      - mqtt_broker
      - redis
    container_name: fornecedor

  almoxarifado:
    build: ./almoxarifado
    depends_on:
      - mqtt_broker
      - redis
    container_name: almoxarifado

  linha_producao:
    build: ./linha_producao
    depends_on:
      - redis
    container_name: linha_producao
