version: '3.8'

services:
  redis:
    image: redis:alpine
    container_name: redis
    networks:
      - redis_network
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: app
    networks:
      - redis_network
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  linha_producao:
    build:
      context: ./linha_producao
      dockerfile: Dockerfile
    container_name: linha_producao
    networks:
      - redis_network
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  fornecedor:
    build:
      context: ./fornecedor
      dockerfile: Dockerfile
    container_name: fornecedor
    networks:
      - redis_network
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  deposito:
    build:
      context: ./deposito
      dockerfile: Dockerfile
    container_name: deposito
    networks:
      - redis_network
    depends_on:
      - redis
    environment:
      -
